print ("This is a code from Rstudio")
print ("This code should be showing up in GitHub for repository RStudioIntegration")
print ("more comments")
print ("This is a code from Rstudio")
print ("This code should be showing up in GitHub for repository RStudioIntegration")
print ("more comments")
print ("This is a code from Rstudio")
print ("This code should be showing up in GitHub for repository RStudioIntegration")
print ("more comments")
#some additional comments from GitHub
